### PR TITLE
Remove the dev/test instances of the CANdy-Dev BC Issuer

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
I listed all three environments, because the verifiers in each environment will only accept a credential from the issuer in their corresponding environment.

**Comment by swcurran** [comment]
Not completely certain what that means, but...  The fact that we have the concept of Dev/Test/Prod for the issuers, and for CANdy (Dev now, but Test, Prod later) makes this a bit confusing, so this is an attempt to minimize that confusion.

The Dev and Test issuers are really just the concern of the BC Developers/SRE folks, not for external folks.  This website is targeting the external folks, and as such, I think it is easier to just mention the "Prod" Issuer linked to the CANdy-Dev environment.  The BC tracking of all of our deployments (in the "Inventory" Trello board) still lists all three Issuer instances.

Make sense?

**Review by flihp27 — COMMENTED** [review]
Since you deleted the dev line, shouldn't you also change the label ('prod') for ('dev') on the line that you are keeping ?

**Comment by swcurran** [comment]
No -- this is the "Prod Issuer" for the "CANdy-Dev" instance.  Nice and confusing...  :-)

**Review by flihp27 — APPROVED** [review]

**Pull request merged**
